# This is a configuration file for setting up DC sweeps
# This will be loaded to plot.py when it starts running

--- # document start
### General variables for testing #################
AgilentE3640A_Addr: "GPIB0::4::INSTR"
folder: "Chip_5" # under results folder
structure: "Si_wg" # the name of the file {structure}_DCSweeps_data


## var  ###########################################
v_start: 0 # start voltage [V]
v_stop: 5  # stop voltage [V]
v_step: 1    # step [V]

## list ###########################################

## dictionary #####################################

... # document end