# This is a configuration file for setting up DC sweeps
# This will be loaded to plot.py when it starts running

--- # document start
### General variables for testing #################
folder: "Chip_5" # under results folder
fname: "Si_wg" # in csv
func:

instr_addrs:
  siggen:
    - "GPIB0::25::INSTR"
    - "GPIB0::20::INSTR"
  osc:
    - "GPIB0::25::INSTR"
    - "GPIB0::20::INSTR"

## var  ###########################################
power: 10 #dBm

v_start: 0 # start voltage [V]
v_stop: 5  # stop voltage [V]
v_step: 1    # step [V]
cycle: 10

lambda_start: 1530 # nm
lambda_end: 1570 # nm
lambda_step: 5 # nm
lambda_speed: 5 # nm/s

## list ###########################################

## dictionary #####################################

... # document end