# This is a configuration file for setting up IV sweeps
# This will be loaded to sweeps_main.py when it starts running

--- # document start

## var  ###########################################
folder: "Christina" # under results folder
fname: "straight" # in csv
func:

instr_addrs:

v_start: 0 # start voltage [V]
v_stop: 5 # stop voltage [V]
v_step: 1 # step [V]
t_step: 0.2 # s

## list ###########################################


## dictionary #####################################

... # document end