# name: Python package

# on: [push]

# jobs:
#   build:
    
#     runs-on: windows-latest
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
      
#       # need to be Python 3.7+ for pytest
#       - name: Setup Python 3.7+
#         uses: actions/setup-python@v3
#         with:
#           cache: 'pip'
      
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Test with pytest
#         run: |
#           python -m pip install --upgrade pytest
#           pytest --ignore=configs --ignore=pyoctal --ignore=results --ignore=tools -s

